export default [
  ["Reactjs & Redux", "Javascript"],
  ["ReactNative & Redux", "Git & GitHub"],
  ["NodeJs & ExpressJs", "Jest, Mocha & Chai"],
  ["HTML & CSS", "Asana, Pivotal Tracker & Jira"],
  ["GraphQL", "Apollo-Client"],
  ["Flask", "Python"],
  ["Heroku", "AWS"],
  ["Serverless", "REST"],
  ["SQLite3", "SQL"],
  ["Postgresql", "Sequelize & SQLAlchemy"],
  ["Mongodb", "Pymongo"],
  ["Circle CI", "Travis CI"],
  ["Docker", "Docker-compose"],
  ["English", "Kinyarwanda"],
  //   ["Kinyarwanda", "Kiswahili"],
];
